### PR TITLE
Search improvements 

### PR DESCRIPTION
**Pull request by reidbaker**
search no longer crashes, is selected after pressing search, results counter added but not working

This is not ready to be pulled in but all the code here will eventually make it into the repo

### CODE REVIEW

**Comment by ejohnson44** [comment]
Looks good to me

**Comment by ejohnson44** [comment]
Actually I lied. I didn't realize that reuslts counter stuff was in here

**Comment by reidbaker** [comment]
@ejohnson44 if you merged my stuff and have results working then I can abandon this and we can take your pull request.

**Comment by ejohnson44** [comment]
Sounds like a plan. I need to do a bit of formatting but other than that it's ready

**Pull request closed without merging**
