### PR TITLE
About page additions

### PR DESCRIPTION
**Pull request by dgreenhalgh**
Fix to #227 and then some.
Cited third party libs, added link to our repo, and added a nifty mailto for support. 

There are a few things that need to be cleaned up here - mostly strings in AboutFragment.java. I tried to take care of that before, but I ran into an issue where the repo links stopped working. I'll check it out in the morning with a fresh set of eyes. Let me know if you see anything that I'm missing.

[Here's a screenshot of how the About page looks now](https://f.cloud.github.com/assets/940735/915466/a87abe2c-fe6e-11e2-9db7-5a04085427d2.png), let me know if there's anything you'd like me to change. Note that the links aren't Linkify links so that we could avoid having to rely on the Internet permissions. 

Also keep in mind that this issue is our last bottleneck to uploading beta, so let's try and get this looked at ASAP.

Thanks! :hamburger:

### CODE REVIEW

**Comment by dgreenhalgh** [comment]
Fixed the strings issue. Please take a look at this and @twrobel3's pull request when you can!

**Comment by theJenix** [comment]
I wouldn't put the 3rd party links under "special thanks".  Can you create a new section called "Credit" or "SoundStream Proudly Uses..." or something like that?

**Comment by reidbaker** [comment]
I agree with @theJenix and I would like to see the about page have the following order. 
*team
*contact
*thanks
*credit

**Comment by theJenix** [comment]
:thumbsup: to @reidbaker's comment.

**Comment by dgreenhalgh** [comment]
Alright I made those changes - [here's a screenshot](https://f.cloud.github.com/assets/940735/921336/8c186bda-fef5-11e2-93ee-ddb0179045b4.png)

**Comment by theJenix** [comment]
We should probably add some language that says "SoundStream is built ontop of the following fine open source projects" or something...so it looks nice, but I don't think that's a showstopper for beta.

**Comment by theJenix** [comment]
:ok_hand:

**Comment by dgreenhalgh** [comment]
I'll just take care of that now while I'm in that code

**Comment by dgreenhalgh** [comment]
Alright done :+1:

**Comment by ejohnson44** [comment]
I like it overall - the only thing that I can really think of is that the 'link' text is unnecessary. The color clearly indicates that it is a link

**Comment by dgreenhalgh** [comment]
That's something I thought of but was unaware if it was necessary because links may have not been expected there. I agree though and I'll make the change

**Comment by dgreenhalgh** [comment]
:+1:

**Comment by reidbaker** [comment]
This is good to go from my perspective. :shipit:

**Comment by dgreenhalgh** [comment]
Anyone else want to weigh in so we can move forward?

**Comment by theJenix** [comment]
looks fine like :wine_glass:

**Pull request merged**
