### PR TITLE
Menu size

### PR DESCRIPTION
**Pull request by ejohnson44**
Menu is now a consistent size

### CODE REVIEW

**Comment by reidbaker** [comment]
Does this handle a horizontal device? Either way looks good. :white_check_mark:

**Comment by ejohnson44** [comment]
That it does :]

**Comment by theJenix** [comment]
This looks good, but I want to :see_no_evil: before pulling it in.

**Comment by theJenix** [comment]
I :see_no_evil:.  Pulling it in.

**Pull request merged**
