### PR TITLE
updated version of app to publish

### PR DESCRIPTION
**Pull request by reidbaker**
This is what is on the play store.

### CODE REVIEW

**Comment by ejohnson44** [comment]
You will probably want to update this once my color sync stuff gets pulled in so that image file isn't so huge - I know that was causing you problems last night

**Comment by reidbaker** [comment]
Already pulled in the image things

**Comment by ejohnson44** [comment]
Oh! Fantastic :monkey:

**Comment by bryansills** [comment]
:thumbsup:

**Comment by dgreenhalgh** [comment]
:shipit:

**Pull request merged**
