### PR TITLE
GPL copyright statements added to top of each source file

### PR DESCRIPTION
**Pull request by dgreenhalgh**
The script works...mostly.

One thing I didn't know about XML files is that the XML tag **has** to be the first line in the file. It's annoying, and it's something that didn't show up in my early tests. 

I fixed the XML files manually, but I haven't rewritten the script yet.

You, my friends, have a choice. Pull this in now, or wait until I rewrite the script, maybe tomorrow.

### CODE REVIEW

**Comment by reidbaker** [comment]
Did you pull down the latest version of the code before you ran this script?

**Comment by dgreenhalgh** [comment]
Yes

**Comment by dgreenhalgh** [comment]
And I'll run it again before we push Alpha to make sure we've got everything covered

**Comment by reidbaker** [comment]
I see one file missing. monkeyTest.py. Its broken so its not a big deal.

**Comment by dgreenhalgh** [comment]
Good catch

**Comment by reidbaker** [comment]
I think we are just waiting on monkeyTest.py then this can be pulled in.

**Comment by dgreenhalgh** [comment]
I got some build errors in PlayStatusMessageTest after I merged in the trunk changes. Don't pull this in just yet, I'm going to wait to pull down some more changes and figure this out.

**Comment by dgreenhalgh** [comment]
Should be good to go now :+1:

**Comment by theJenix** [comment]
:lock:s good to me.

**Pull request merged**
