### PR TITLE
Menu user fix

### PR DESCRIPTION
**Pull request by ejohnson44**
Fixed the bug in the user list display in the menu fragment

### CODE REVIEW

**Comment by dgreenhalgh** [comment]
:+1:

**Comment by theJenix** [comment]
Can you post a screenshot of what this looks like?  It sounds right, but i'd like to see it.

**Comment by ejohnson44** [comment]
menu_fix

**Comment by theJenix** [comment]
Beeeeeeeautiful.  This is a- :ok: with me.

**Pull request merged**
