### PR TITLE
GPL copyright statements and import cleanup

### PR DESCRIPTION
**Pull request by dgreenhalgh**
Two features here: the addition of copyright statements to our documentation, and a comprehensive cleanup deleting the import statements we haven't been using.

### CODE REVIEW

**Comment by ejohnson44** [comment]
All looks good to me!

**Comment by bryansills** [comment]
looks good to me.

**Comment by dgreenhalgh** [comment]
There are some merge conflicts, let me fix them and this should be good to go :basketball:

**Comment by dgreenhalgh** [comment]
Should be good to go now if someone wants to pull it in :basketball:

**Pull request merged**
