### PR TITLE
Clickable area

### PR DESCRIPTION
**Pull request by ejohnson44**
increased the size of the clickable areas on the buttons

### CODE REVIEW

**Comment by reidbaker** [comment]
So It looks good to me and by good I mean I have no idea how to code review xml changes. You are a wizard

**Comment by dgreenhalgh** [comment]
I'm in the same boat as Reid, but I like this

**Comment by reidbaker** [comment]
http://www.youtube.com/watch?feature=player_detailpage&v=WX_OW_IuF5A#t=8s

**Comment by reidbaker** [comment]
The image does not get bigger I am pulling this in.

**Pull request merged**
