### PR TITLE
Discoverable discount

### PR DESCRIPTION
**Pull request by reidbaker**
Make guests discoverable for 30 seconds instead of for 5 min

### CODE REVIEW

**Comment by theJenix** [comment]
As part of this fix, can we also reenable the connect button on the ConnectFragment after 30 seconds?  We can't get feedback when discoverability is disabled unless we poll the Bluetooth scan mode, which is probably more correct, but I think its fine to just reenable the button after 30 seconds.

**Comment by reidbaker** [comment]
So I started working on the playbar fragment on the guests having the correct song. It was way bigger than I was thinking so I got it to a stable place and when this gets pulled in I will make that its own branch

**Comment by dgreenhalgh** [comment]
Conflicts arose after #88 was pulled in

**Comment by reidbaker** [comment]
This can now be pulled in

**Comment by dgreenhalgh** [comment]
:snowflake: :snowflake: :snowflake: :snowflake: :snowflake: :snowflake: :snowflake: :snowflake: :snowflake: :snowflake: :snowflake: :snowflake: :snowflake: :snowflake:

**Pull request merged**
