### PR TITLE
fixed issue causing immediate disconnection of socket

### PR DESCRIPTION
**Pull request by theJenix**
issue was: the code, as written, was disconnecting as soon as it processed a message.  This has been fixed in the commit.

### CODE REVIEW

**Comment by reidbaker** [comment]
Thanks for figuring this out Jesse. I can check this out tonight

**Comment by theJenix** [comment]
No problem.  I would have had it up earlier but I had a hell of a time testing with my Nexus 4.  When my Nexus 4 was a host, transfers would stall about halfway through.  I then tested between two other Nexus 4 devices and everything seemed great.  If you see anything like the problem I just described, let me know and I'll dig back in.

**Comment by dgreenhalgh** [comment]
:+1:

**Comment by reidbaker** [comment]
:hamburger:

**Pull request merged**
