### PR TITLE
Monster refactor

### PR DESCRIPTION
**Pull request by reidbaker**
Change our package from com.lastcrusade to com.thelastcrusade and made the version number 1.

### CODE REVIEW

**Comment by dgreenhalgh** [comment]
Thanks a lot man. To fill you guys in, we ran in a problem uploading the APK due to an issue with our version numbering and the fact that our package names conflicted with those of SoundStream Alpha. This big naming refactor is the most time-efficient way to solve this issue. 

Let's please try and pull this in ASAP so that we can push to the Play Store

**Comment by theJenix** [comment]
Looks good to me, and builds on my machine.  Two enthusiastic :thumbsup:

**Comment by dgreenhalgh** [comment]
I'll be running through some quick tests of this version of the code tonight before this goes out

**Comment by dgreenhalgh** [comment]
Lady and gentlemen, we have a published beta.

**Pull request merged**
