### PR TITLE
Fixed bug where the Playlist object was reassigning entry ids sent from the host

### LINKED ISSUE #165: App Crash on Played Song Removal (Guest)
When a guest attempts to remove a song from the playlist that has already been played  the app crashes

### LINKED ISSUE #166: Weird Transferring State
When a guest adds a song from the host phone, it shows up as transferring on the guest, but not on the host. Once the song is played, it shows as transferring on the host

### LINKED ISSUE #168: Transferred and Played States (Guest)
Transferred and Played states do not automatically update on the guest. They do update after the guest has added a new song to the playlist

### LINKED ISSUE #173: Guest playlist load status not updated
To reproduce:
1. Establish a network with one guest.
2. Open the playlist on the guest, and library on the host.
3. From the host, add a song that exists on the host phone.

Observe that the guest playlist shows the song is perpetually loading, until the song is played.  This is a cosmetic issue, but can create confusion for the user.

### LINKED ISSUE #178: Crash on host when swiping to remove playlist entry on guest
To reproduce:
1. Establish a network with one guest.
2. From the guest, add 2 songs to the playlist and press play.
3. From the guest, swipe to remove the 2nd playlist entry.
4. From the guest, add a different song to the playlist.  This will become a new 2nd playlist entry.
5. From the guest, swipe to remove the new 2nd playlist entry.

The app on the host will force close.

Exception trace:
E/AndroidRuntime(19935): FATAL EXCEPTION: main
E/AndroidRuntime(19935): java.lang.NullPointerException
E/AndroidRuntime(19935):    at com.lastcrusade.soundstream.util.SongMetadataUtils.isTheSameEntry(SongMetadataUtils.java:57)
E/AndroidRuntime(19935):    at com.lastcrusade.soundstream.service.PlaylistService.isCurrentEntry(PlaylistService.java:413)
E/AndroidRuntime(19935):    at com.lastcrusade.soundstream.service.PlaylistService.access$400(PlaylistService.java:56)
E/AndroidRuntime(19935):    at com.lastcrusade.soundstream.service.PlaylistService$6.onReceiveAction(PlaylistService.java:310)
E/AndroidRuntime(19935):    at com.lastcrusade.soundstream.util.BroadcastRegistrar$1.onReceive(BroadcastRegistrar.java:83)
E/AndroidRuntime(19935):    at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
E/AndroidRuntime(19935):    at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
E/AndroidRuntime(19935):    at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
E/AndroidRuntime(19935):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19935):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(19935):    at android.app.ActivityThread.main(ActivityThread.java:5041)
E/AndroidRuntime(19935):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(19935):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(19935):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime(19935):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime(19935):    at dalvik.system.NativeStart.main(Native Method)

### PR DESCRIPTION
**Pull request by theJenix**
This was the source of a number of state issues, and the crashes when attempting to remove items, because the entry ids were pulled out of sync after the guest removed an item.

fixes #178
fixes #166
fixes #168
fixes #173
fixes #165

### CODE REVIEW

**Comment by dgreenhalgh** [comment]
That's a lotta fixes

**Comment by theJenix** [comment]
@reidbaker This fixes a number of the issues assigned to you...please take a look and and confirm.

**Comment by theJenix** [comment]
@dgreenhalgh Yea, this was one of those tiny bugs that affects EVERYTHING.  Like a deer tick, but in code.

**Comment by ejohnson44** [comment]
looks good to me :tada:

**Comment by reidbaker** [comment]
I will verify the bugs assigned to me later but this looks good so I am pulling it in.

**Pull request merged**
