### PR TITLE
Join as <bluetooth name> in connect fragment

### PR DESCRIPTION
**Pull request by reidbaker**
I got this one done first to get back in the swing of coding.

### CODE REVIEW

**Comment by reidbaker** [comment]
connect_as_working

**Comment by dgreenhalgh** [comment]
Anyone think that this makes more sense with quotes around the name?

Meaning:

Join as "Nexus 4"

rather than 

Join as Nexus 4

I believe the default Bluetooth name is the device name, so the fact that the user would be identified by a Bluetooth name rather than a device name may be lost without quotes.

**Comment by theJenix** [comment]
I think I agree with David...the quotes make sense, as we're specifying a specific string that will be used to identify this phone.

**Comment by ejohnson44** [comment]
I agree with the others, but other than that this looks good to me

**Comment by reidbaker** [comment]
This is now ready to pull in.

**Comment by theJenix** [comment]
:beers:

**Pull request merged**
