### PR TITLE
Added preferences file to insert the GPL license at the top of each new file

### PR DESCRIPTION
**Pull request by theJenix**
What it says on the tin.

### CODE REVIEW

**Comment by dgreenhalgh** [comment]
I refuse to pull this in out of spite :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire:

**Comment by theJenix** [comment]
Oh man.  Send in the :fire_engine:.

**Comment by dgreenhalgh** [comment]
Send in the :horse: :shit:

**Comment by reidbaker** [comment]
Don't worry @bryansills will still need it.

**Pull request merged**
